#!/usr/bin/env python3
"""
Auto-Fix Agent: Analyzes test failures and generates fixes
Spawned by GitHub Actions when Playwright tests fail
"""

import json
import subprocess
import sys
from pathlib import Path

def analyze_failures(test_results_dir):
    """Parse Playwright test results"""
    results_file = Path(test_results_dir) / "results.json"
    
    if not results_file.exists():
        print("❌ No results.json found")
        return []
    
    with open(results_file) as f:
        data = json.load(f)
    
    failures = []
    for suite in data.get('suites', []):
        for spec in suite.get('specs', []):
            if not spec.get('ok', True):
                failures.append({
                    'title': spec.get('title'),
                    'file': spec.get('file'),
                    'error': spec.get('tests', [{}])[0].get('results', [{}])[0].get('error', {})
                })
    
    return failures

def spawn_fix_subagent(failure):
    """Spawn OpenClaw subagent to fix the issue"""
    error_msg = failure['error'].get('message', '')
    stack = failure['error'].get('stack', '')
    
    task = f"""
Playwright test failed: {failure['title']}

File: {failure['file']}

Error: {error_msg}

Stack trace:
{stack}

TASK:
1. Analyze the failure (selector issue, timing, logic bug, etc.)
2. Identify root cause
3. Generate a fix (code changes needed)
4. Create a git branch with the fix
5. Return: {{ "branch": "fix/test-failure-123", "description": "...", "files": {{...}} }}

Do NOT commit yet - return the fix for human review.
"""
    
    result = subprocess.run(
        ["openclaw", "spawn", "--task", task, "--model", "sonnet", "--json"],
        capture_output=True,
        text=True,
        timeout=300
    )
    
    if result.returncode != 0:
        print(f"❌ Subagent failed: {result.stderr}")
        return None
    
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        print(f"❌ Invalid JSON from subagent: {result.stdout}")
        return None

def create_pr_with_fix(branch_name, fix_description, fixes):
    """Create GitHub PR with the fix"""
    # Create branch
    subprocess.run(["git", "checkout", "-b", branch_name], check=True)
    
    # Apply fixes
    for file_path, content in fixes.items():
        Path(file_path).write_text(content)
    
    # Commit
    subprocess.run(["git", "add", "."], check=True)
    subprocess.run(["git", "commit", "-m", f"Fix: {fix_description}"], check=True)
    
    # Push
    subprocess.run(["git", "push", "origin", branch_name], check=True)
    
    # Create PR via GitHub CLI
    subprocess.run([
        "gh", "pr", "create",
        "--title", f"🤖 Auto-fix: {fix_description}",
        "--body", f"Generated by Fix Agent after test failure.\n\nReview before merging.\n\n**Changes:**\n- {fix_description}",
        "--label", "auto-fix",
        "--label", "test-failure"
    ], check=True)

def main():
    test_results = Path("test-results")
    
    if not test_results.exists():
        print("✅ No test failures found")
        sys.exit(0)
    
    failures = analyze_failures(test_results)
    
    if not failures:
        print("✅ No failures to fix")
        sys.exit(0)
    
    print(f"🔧 Found {len(failures)} test failures")
    
    for i, failure in enumerate(failures, 1):
        print(f"\n{'='*60}")
        print(f"Analyzing failure {i}/{len(failures)}: {failure['title']}")
        print(f"{'='*60}")
        
        fix_result = spawn_fix_subagent(failure)
        
        if not fix_result:
            print(f"❌ Failed to generate fix for: {failure['title']}")
            continue
        
        branch_name = fix_result.get('branch', f'fix/test-failure-{i}')
        fix_desc = fix_result.get('description', 'Test failure fix')
        fixes = fix_result.get('files', {})
        
        if not fixes:
            print(f"⚠️  No file changes generated for: {failure['title']}")
            continue
        
        # Create PR
        try:
            create_pr_with_fix(branch_name, fix_desc, fixes)
            print(f"✅ Created PR: {branch_name}")
        except subprocess.CalledProcessError as e:
            print(f"❌ Failed to create PR: {e}")
            continue
    
    print(f"\n{'='*60}")
    print(f"✅ Fix Agent completed: {len(failures)} failures analyzed")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()
